export const events = [
    {
      id: 1,
      title: "Beautiful Night",
      description: "Enjoy Music",
      category: "Music",
      date: "2024-11-20",
      seats: 10,
      price: 50,
    },
    {
      id: 2,
      title: "Art Workshop",
      description: "Learn painting techniques.",
      category: "Art",
      date: "2024-10-25",
      seats: 5,
      price: 30,
    },
    {
      id: 3,
      title: "Tech Conference",
      description: "Explore the latest in tech.",
      category: "Technology",
      date: "2024-11-01",
      seats: 0,
      price: 100,
    },
    {
        id: 4,
        title: "Tech Conference",
        description: "Explore the latest in tech.",
        category: "Technology",
        date: "2024-11-01",
        seats: 0,
        price: 100,
      },
      {
        id: 5,
        title: "cities",
        description: "Explore the latest in tech.",
        category: "Technology",
        date: "2024-11-01",
        seats: 0,
        price: 100,
      },
  ];